package org.api.productcatalogservice.util;

public enum CatageoryType {
    ELECTRONIC,ELECTRONIC_CATALOG,MICROSOFT,MICROSOFT_CATALOG,
    MECHANICAL, MECHANICAL_CATALOG, BIOMETRIC, BIOMETRIC_CATALOG,
    BIOLOCATAGEORY_TYPE, CHEMISTRY, CHEMISTRY_CATALOG,HUMAN;
}
